# Generated by Django 2.0 on 2020-10-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200807_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewcount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
