# Generated by Django 2.0 on 2020-10-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_post_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=200)),
                ('viewcount', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
