# Generated by Django 2.0 on 2020-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20201029_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewcount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
