# Generated by Django 2.0 on 2020-10-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20201030_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag_let_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
