# Generated by Django 2.0 on 2020-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_post_tag_let_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag_let_one',
            field=models.CharField(blank=True, choices=[('Natural', 'Natural'), ('Historical', 'Historical'), ('Industrial', 'Industrial')], max_length=200, null=True),
        ),
    ]
